FROM python:latest

RUN mkdir /workdir

RUN pip install --no-cache-dir \
ipython \
psutil \
sympy \
numpy \
pillow \
requests \
pyyaml \
colorama \
passlib \
cryptography \
matplotlib

WORKDIR /workdir
