FROM python:3-stretch
SHELL ["/bin/bash", "-c"]
RUN mkdir /workdir

RUN apt purge -y python* && \
    rm -rf /usr/bin/python

RUN ln -s /usr/local/bin/python /usr/bin/python


RUN pip install --no-cache-dir \
            ansible \
            boto \
            boto3 \
            docker-py \
            mysql-connector-python \
            psycopg2

RUN mkdir /root/.aws

WORKDIR /workdir
