FROM python:3-alpine

RUN mkdir /workdir
RUN mkdir /root/.aws
RUN ln -s /usr/local/bin/python /usr/bin/python
RUN apk update; apk add --no-cache \
  musl-dev \
  bash \
  postgresql-dev \
  postgresql-libs \
  gcc libffi-dev \
  make \
  libssl1.0\
  openssh-client \
  sshpass \
  curl

SHELL ["/bin/bash", "-c"]

RUN pip install --no-cache-dir \
    boto \
    boto3 \
    docker-py \
    mysql-connector-python \
    jmespath \
    psycopg2-binary

RUN pip install ansible

RUN apk del musl-dev postgresql-dev gcc libffi-dev make
RUN adduser -h /home/ansible -D -u 1000 -s /bin/bash ansible
USER ansible
WORKDIR /workdir
